export const UPDATE_ACTIVITIES = 'UPDATE_ACTIVITIES';
export const SET_STATE = 'SET_STATE';
export const START_FETCHING_LOADING = 'START_FETCHING_LOADING';
export const STOP_FETCHING_LOADING = 'STOP_FETCHING_LOADING';